stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/info:0.0.5
      pushRemote: true
      registry: index.docker.io
timeout: 60
